spring:
    application:
        name: webapi
server:
    port: 8080
springdoc:
    # The raw OpenAPI descriptions (default path: /v3/api-docs)
    api-docs:
        path: /api-docs
    # With Swagger UI (default path: /swagger-ui)
    swagger-ui:
        path: /swagger-ui